FROM jenkins/jenkins:lts

USER root

# Install docker + git
RUN apt-get update && \
    apt-get install -y git docker.io && \
    apt-get clean

# Give jenkins user permissions to run docker
RUN usermod -aG docker jenkins

USER jenkins

