{{- if (.Values.httpRoute | default dict).enabled | default false -}}
{{- $fullName := include "my-app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  rules:
    - backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
          weight: 1
{{- end }}
