{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: {{ .Values.cronjob.image }}
              args:
{{- range .Values.cronjob.command }}
                - {{ . | quote }}
{{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
{{- end }}
