{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "my-app.fullname" . }}
spec:
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "my-app.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
